//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DarkDemo
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblCustomerCheck
    {
        public int CheckID { get; set; }
        public int CustomerId { get; set; }
        public string CompanyName { get; set; }
        public Nullable<double> CheckAmount { get; set; }
        public Nullable<double> FeePercentage { get; set; }
        public Nullable<double> FeeAmount { get; set; }
        public Nullable<double> NetAmount { get; set; }
        public Nullable<System.DateTime> CashedDate { get; set; }
        public string CashedBy { get; set; }
        public string CheckNo { get; set; }
    
        public virtual tblCustomerInfo tblCustomerInfo { get; set; }
    }
}
